import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import '../assets/scss/global.scss'

import MeetingButton from '@/components/MeetingButton'

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: "normal",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className='body-container'>
        <MeetingButton font={ roboto.className } />
        {children}
      </body>
    </html>
  );
}
